// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xafiddtuadioiitvshqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZmlkZHR1YWRpb2lpdHZzaHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODAxNDQsImV4cCI6MjA1ODM1NjE0NH0.gn_I43pYa5CMboBL0Wwu5qnuC749HD1g0KSlj6cEQUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);